apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stoneflow-data-pvc
  namespace: stoneflow
  labels:
    app: stoneflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
